[features]
seeds = false
[programs.localnet]
token3 = "G28ceN5471mPMKhSThZu4tvzK6Skbxrr8qy4abskVsYJ"

[programs.devnet]
token3 = "G28ceN5471mPMKhSThZu4tvzK6Skbxrr8qy4abskVsYJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
